### ISSUE TITLE
Do not start the timer unless you can actually fetch the inputs

### ISSUE THREAD

**Issue by kientuong114** [davidemerli/human-aoc#5]
Currently, when starting a new challenge, the website will try to fetch the input, and regardless of success, it will start the timer.
If people input the cookie incorrectly (or have an old one that has been revoked), the timer will start even though the user cannot access their input.

The website should recognize that the cookie is invalid and ask the user to add a new one, without starting the timer.

**Comment by Giuzzilla** [comment]
+1 my timer for day 1 be like 
![image](https://github.com/davidemerli/human-aoc/assets/6185775/a3d917d0-91f0-4848-ab39-a4f801442989)

**Comment by davidemerli** [comment]
Fixed by throwing an error if cookie is invalid. A better UX will be taken into consideration in the next full rewrite, for now it does the job

https://github.com/davidemerli/human-aoc/commit/6784eb31821015855927f1989fd3fb3d4c7f155f
